### ISSUE TITLE
library dependency for building

### ISSUE THREAD

**Issue by chenmagi** [geziangfinn/easyPlace#1]
Hi

   Could you please let me know the library dependency on building this project?  My environment is Ubuntu 22.04 and I have installed libeigen3-dev. 

Best,

Magi

**Comment by geziangfinn** [comment]
We don't have a clear list, but GCC, CMake, X11 and boost are necessary, and I believe you can install all of them with 'apt install' on Ubuntu. I suggest you try to build it, and let me know if you run into any dependency problems in this issue. I think normally you won't have too much problems on a Ubuntu machine.

**Comment by chenmagi** [comment]
I am able to compile the project successfully by changing the directory for the make command. I was initially in the 'build' directory but needed to be in 'build/main'.

Thank you for the reply.
