### ISSUE TITLE
baseline

### ISSUE THREAD

**Issue by Super-Karl** [geziangfinn/easyPlace#2]
Hello, excellent work! Have you conducted actual experiments? Do you have experimental data? Would you recommend using the experimental results of this project as a baseline for academic papers?

**Comment by geziangfinn** [comment]
Hello. We tested our code on ISPD2002, ICCAD2004, ISPD2005, ISPD2006 and the MMS benchmarks. All benchmarks we have used are of bookshelf format and are available online. And we believe we have achieved decent performance in terms of HPWL compared with the original ePlace. You can try it on your machine and see if it meets your need.

**Comment by Super-Karl** [comment]
太感谢了！thank you so much！

**Comment by Super-Karl** [comment]
> Hello. We tested our code on ISPD2002, ICCAD2004, ISPD2005, ISPD2006 and the MMS benchmarks. All benchmarks we have used are of bookshelf format and are available online. And we believe we have achieved decent performance in terms of HPWL compared with the original ePlace. You can try it on your machine and see if it meets your need.

太感谢了！thank you thank you！

**Comment by geziangfinn** [comment]
You are welcome. Solved and closed.
